print:
  printer-name: "GP-C58 Series"
  max-retry: 3 # 最大重试次数
  queue:
    offer-timeout: 5  # 设置等待5秒
  qrcode-path: classpath:static/qrcode.jpg  # 二维码图片路径

# 远程服务器配置
remote:
  server:
#    url: http://119.91.239.47 # 远程服务器URL 暂时放在测试打印内容客服的项目下
    url: http://localhost:23335 # 本地服务器URL
    ws-path: /print-ws # WebSocket路径
  auth:
    enabled: false # 是否启用认证
    username: admin # 认证用户名
    password: password # 认证密码
  connection:
    retry-interval: 500 # 连接重试间隔(毫秒)
  poll:
    interval: 10000 # 轮询间隔(毫秒)

# 服务端口配置
server:
  port: 23333

# 日志配置
logging:
  file:
    name: ${user.home}/AppData/Roaming/electron-print-app/logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    org.example.print: INFO
    org.example.print.service.RemoteDataService: DEBUG

# 应用数据存储路径（这个只是默认值，会被命令行参数覆盖）
app:
  data:
    dir: ${user.home}/AppData/Roaming/electron-print-app/data
